-------------------------------------------------------------------------------
Test set: com.google.qa.testcases.MyTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.905 sec <<< FAILURE! - in com.google.qa.testcases.MyTest
test on test(com.google.qa.testcases.MyTest)(com.google.qa.testcases.MyTest)  Time elapsed: 0.579 sec  <<< FAILURE!
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Sufians-MacBook-Pro.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at com.google.qa.testcases.MyTest.SetUp(MyTest.java:38)
Caused by: java.net.ConnectException: Failed to connect to /192.168.178.95:4444
	at com.google.qa.testcases.MyTest.SetUp(MyTest.java:38)
Caused by: java.net.ConnectException: Network is unreachable (connect failed)
	at com.google.qa.testcases.MyTest.SetUp(MyTest.java:38)

testDBUnit on testDBUnit(com.google.qa.testcases.MyTest)(com.google.qa.testcases.MyTest)  Time elapsed: 0.011 sec  <<< FAILURE!
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Sufians-MacBook-Pro.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at com.google.qa.testcases.MyTest.SetUp(MyTest.java:38)
Caused by: java.net.ConnectException: Failed to connect to /192.168.178.95:4444
	at com.google.qa.testcases.MyTest.SetUp(MyTest.java:38)
Caused by: java.net.ConnectException: Network is unreachable (connect failed)
	at com.google.qa.testcases.MyTest.SetUp(MyTest.java:38)

